collector = "https://194.182.167.15.nip.io/incoming_data"
global_interval = 1000

[endpoints.small]
url = "https://bing.com"
iterations = 5
interval = 0

[endpoints.ipfs-1mb]
url = "https://cloudflare-ipfs.com/ipfs/QmVkbauSDEaMP4Tkq6Epm9uW75mWm136n81YH8fGtfwdHU"
iterations = 1
interval = 0

[endpoints.ipfs-5mb]
url = "https://cloudflare-ipfs.com/ipfs/QmS2s8GRYHEurXL7V1zUtKvf2H1BGcQc5NN1T1hiSnWvbd"
iterations = 1
interval = 0

[endpoints.ipfs-20mb]
url = "https://cloudflare-ipfs.com/ipfs/QmPxHUfEJxvT6DjvCgExuSRkhxbrHgC4UHSX8yDgY1VQ2p"
iterations = 1
interval = 0
