collector = "http://127.0.0.1:8080/incoming_data"
username = "autotest"
password = "testing"

[endpoints.small]
url = "https://bing.com"
iterations = 10
avg_interval = 5

#endpoints.big_google]
#url = "https://dl.google.com/android/studio/maven-google-com/stable/offline-gmaven-stable.zip"
#iterations = 1
#avg_interval = 5

[endpoints.big_hetzner]
url = "http://speed.hetzner.de/100MB.bin"
iterations = 1
avg_interval = 5
